/**
 * Sprint 11 Phase 2 — writes the site's current content into the ACF fields
 * registered by wp-plugin/megc-site-content, then reads every field back and
 * diffs it against the payload. Source of truth for values: the same config
 * files and JSX strings the live site renders today (configs imported
 * directly; JSX strings via scripts/wp-migrate/hardcoded-strings.json,
 * generated by extract-hardcoded.mjs).
 *
 * Runs in GitHub Actions (wp-migrate.yml) where WP_APP_USER/WP_APP_PASSWORD
 * live and the runner can reach admin.megcmusic.com. Locally:
 *
 *   node --env-file=.env.local --import tsx scripts/wp-migrate/migrate-content.ts --dry-run
 *
 * --dry-run performs auth + all lookups and prints the payloads, writing
 * nothing. Idempotent: re-running writes the same values again (safe), and
 * the read-back diff is the pass/fail signal either way. Exits non-zero on
 * any auth failure, missing lookup, or read-back mismatch.
 */

import { readFileSync } from "node:fs";
import path from "node:path";

import { ARTIST_LINKS, RELEASES } from "../../src/config/discography";
import { RELEASE_DETAILS } from "../../src/config/releases";
import { REVIEWS } from "../../src/config/reviews";
import { LIVE_FORMATS } from "../../src/config/formats";
import { COLLAB_GROUPS, CAVE_CREW_URL } from "../../src/config/collaborate";

const DRY_RUN = process.argv.includes("--dry-run");
const ORIGIN = process.env.NEXT_PUBLIC_WP_ORIGIN || "https://admin.megcmusic.com";
const API = `${ORIGIN}/wp-json/wp/v2`;
const USER = process.env.WP_APP_USER;
const PASS = process.env.WP_APP_PASSWORD;
if (!USER || !PASS) {
  console.error("Missing WP_APP_USER / WP_APP_PASSWORD");
  process.exit(1);
}
const AUTH = "Basic " + Buffer.from(`${USER}:${PASS}`).toString("base64");

const STRINGS = JSON.parse(
  readFileSync(path.join(import.meta.dirname, "hardcoded-strings.json"), "utf8"),
);


async function wp(pathname: string, init: RequestInit = {}, attempt = 0): Promise<any> {
  const res = await fetch(`${API}${pathname}`, {
    ...init,
    headers: {
      Authorization: AUTH,
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
    signal: AbortSignal.timeout(20000),
  }).catch(async (e) => {
    if (attempt < 1) return null;
    throw e;
  });
  if (res === null) return wp(pathname, init, attempt + 1);
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`${init.method ?? "GET"} ${pathname} → HTTP ${res.status}: ${body.slice(0, 300)}`);
  }
  return res.json();
}

async function pageIdBySlug(slug: string): Promise<number> {
  const rows = await wp(`/pages?slug=${slug}&status=publish,draft,private&_fields=id,slug`);
  if (!rows.length) throw new Error(`no WP page with slug ${slug}`);
  return rows[0].id;
}

async function productIdBySlug(slug: string): Promise<number> {
  const rows = await wp(`/product?slug=${slug}&_fields=id,slug`);
  if (!rows.length) throw new Error(`no product with slug ${slug}`);
  return rows[0].id;
}

async function ensureHeroPhoto(): Promise<number> {
  const rows = await wp(`/media?search=meghan-hero&per_page=20&_fields=id,source_url`);
  const hit = rows.find((r: any) => (r.source_url ?? "").includes("meghan-hero"));
  if (hit) return hit.id;
  if (DRY_RUN) {
    console.log("[dry-run] would upload public/images/hero/meghan-hero.jpg");
    return -1;
  }
  const bytes = readFileSync("public/images/hero/meghan-hero.jpg");
  const res = await fetch(`${API}/media`, {
    method: "POST",
    headers: {
      Authorization: AUTH,
      "Content-Type": "image/jpeg",
      "Content-Disposition": 'attachment; filename="meghan-hero.jpg"',
    },
    body: bytes,
    signal: AbortSignal.timeout(60000),
  });
  if (!res.ok) throw new Error(`hero upload → HTTP ${res.status}: ${(await res.text()).slice(0, 300)}`);
  const media = await res.json();
  console.log(`uploaded meghan-hero.jpg → attachment ${media.id}`);
  return media.id;
}

async function ensureSitePoetryPage(): Promise<number> {
  const rows = await wp(`/pages?slug=site-poetry&status=publish,draft,private&_fields=id,slug`);
  if (rows.length) return rows[0].id;
  if (DRY_RUN) {
    console.log("[dry-run] would create page site-poetry");
    return -1;
  }
  const page = await wp(`/pages`, {
    method: "POST",
    body: JSON.stringify({
      title: "Site: Poetry",
      slug: "site-poetry",
      status: "publish",
      content:
        "<p>This page holds the megcmusic.com Poetry page's content — edit the boxes below. Visitors see megcmusic.com/poetry.</p>",
    }),
  });
  console.log(`created site-poetry page → ${page.id}`);
  return page.id;
}


async function main() {
  // 1 — auth (context=edit proves the application password, not just anonymous read)
  const me = await wp(`/users/me?context=edit&_fields=id,name`);
  console.log(`authenticated as ${me.name} (user ${me.id})`);

  // 2 — lookups
  const ids = {
    home: 4, booking: 5, media: 10, shows: 20, epk: 608, shop: 1847,
    solo: 2931, band: 2939, collabs: 3742, fycShadows: 4350, kindred: 4378,
    sfts2: 4395, breaker: 4403, aint: 4411, fycKindred: 4566, videos: 5560, music: 5562,
  };
  const productIds: Record<string, number> = {};
  for (const slug of ["shadows-of-a-ghost-town-cd", "kindred-spirits-ep", "songs-from-the-sofa-cd"]) {
    productIds[slug] = await productIdBySlug(slug);
  }
  // Still ensured (a fresh install needs the hero in the media library for the
  // home page's Site photo field), but its id is no longer written from here —
  // Phase 3 made WordPress the source for the home surface.
  await ensureHeroPhoto();
  // Still ensured (a fresh install needs the page Meg edits to exist), but its
  // content is no longer written from here — Phase 3 made WordPress the source.
  await ensureSitePoetryPage();
  const releasePageIds: Record<string, number> = {
    "shadows-of-a-ghost-town": ids.fycShadows,
    "kindred-spirits": ids.kindred,
    // canonical page for Songs from the Sofa is songs-from-the-sofa-2 (decisions.md 2026-08-29)
    "songs-from-the-sofa": ids.sfts2,
    "breaker-breaker": ids.breaker,
    "aint-going-back": ids.aint,
  };

  // 3 — payloads (field names match wp-plugin/megc-site-content/acf-json)
  // NOTE: the FYC campaign payloads and lyric-sheet alts were removed after
  // Phase 3 made WordPress their source of truth (migrated + verified in run
  // 33978411393) — a re-run must never overwrite Meg's edits with stale data.
  // Unified release registry: discography order (year desc), then paged singles —
  // renders back to today's Discography (EYATM/LP/EPs) and Singles (breaker, aint) lists.
  const releaseRows = [
    { title: "Everything You Are To Me", year: "2026", kind: "SINGLE", release_page: null, product: null, spotify_url: "", apple_url: "" },
    ...RELEASES.filter((r) => r.detailSlug).map((r) => ({
      title: r.title,
      year: r.year,
      kind: r.type,
      release_page: releasePageIds[r.detailSlug!],
      product: r.productSlug ? productIds[r.productSlug] : null,
      spotify_url: r.spotify ?? "",
      apple_url: r.apple ?? "",
    })),
    ...RELEASE_DETAILS.filter((r) => r.type === "SINGLE").map((r) => ({
      title: r.title,
      year: r.year,
      kind: r.type,
      release_page: releasePageIds[r.slug],
      product: null,
      spotify_url: r.spotify ?? "",
      apple_url: r.apple ?? "",
    })),
  ];

  const reviewsFor = (slug: string) =>
    (REVIEWS[slug] ?? []).map((r) => ({
      quote_or_accolade: r.quote ?? r.accolade ?? "",
      source: r.source,
      link: r.href ?? "",
    }));

  const writes: Array<{ page: number; label: string; acf: Record<string, unknown> }> = [
    // NOTE: the home payload was removed after Phase 3 made WordPress the
    // source of truth for the home surface (migrated + verified in run
    // 33978411393) — a re-run must never overwrite Meg's edits with stale data.
    {
      page: ids.music, label: "music",
      acf: {
        page_lede: STRINGS.music.page_lede,
        releases: releaseRows,
        artist_spotify: ARTIST_LINKS.spotify,
        artist_apple: ARTIST_LINKS.apple,
        artist_amazon: ARTIST_LINKS.amazon,
        meta_title: STRINGS.music.meta.title,
        meta_description: STRINGS.music.meta.description,
      },
    },
    { page: ids.fycShadows, label: "reviews:shadows", acf: { reviews: reviewsFor("shadows-of-a-ghost-town") } },
    { page: ids.kindred, label: "reviews:kindred", acf: { reviews: reviewsFor("kindred-spirits") } },
    {
      page: ids.solo, label: "format:solo",
      acf: { format_label: LIVE_FORMATS[0].label, format_blurb: LIVE_FORMATS[0].blurb },
    },
    {
      page: ids.band, label: "format:band",
      acf: { format_label: LIVE_FORMATS[1].label, format_blurb: LIVE_FORMATS[1].blurb },
    },
    {
      page: ids.collabs, label: "work-with-me",
      acf: {
        collab_groups: COLLAB_GROUPS.map((g) => ({
          heading: g.heading,
          blurb: g.blurb,
          // Config offerings are single strings — stored whole in `title`, detail empty.
          offerings: g.offerings.map((o) => ({ title: o, detail: "" })),
        })),
        cave_crew_url: CAVE_CREW_URL,
      },
    },
    // NOTE: the press-kit, media and videos payloads were removed as Phase 3
    // made WordPress the source of truth for those surfaces (migrated +
    // verified in run 33978411393) — a re-run must never overwrite Meg's edits
    // with stale data.
    {
      page: ids.booking, label: "booking",
      acf: {
        page_lede: STRINGS.booking.page_lede,
        intro: STRINGS.booking.intro,
        include_items: STRINGS.booking.include_items.map((i: string) => ({ item: i })),
        fact_formats: STRINGS.booking.facts.formats,
        fact_based: STRINGS.booking.facts.based,
        fact_plays: STRINGS.booking.facts.plays,
        meta_title: STRINGS.booking.meta.title,
        meta_description: STRINGS.booking.meta.description,
      },
    },
    {
      page: ids.shows, label: "shows",
      acf: {
        page_lede: STRINGS.shows.page_lede,
        meta_title: STRINGS.shows.meta.title,
        meta_description: STRINGS.shows.meta.description,
      },
    },
    {
      page: ids.shop, label: "shop",
      acf: {
        page_lede: STRINGS.shop.page_lede,
        meta_title: STRINGS.shop.meta.title,
        meta_description: STRINGS.shop.meta.description,
      },
    },
  ];


  if (DRY_RUN) {
    for (const w of writes) console.log(`[dry-run] page ${w.page} (${w.label}):`, JSON.stringify(w.acf).slice(0, 200));
    console.log("DRY RUN COMPLETE — auth + all lookups succeeded, nothing written.");
    return;
  }

  // 5 — writes (two writes to page 4350 merge: ACF updates only the keys sent)
  for (const w of writes) {
    await wp(`/pages/${w.page}`, { method: "POST", body: JSON.stringify({ acf: w.acf }) });
    console.log(`wrote ${w.label} → page ${w.page}`);
  }

  // 6 — read back and diff (verify at the destination)
  const failures: string[] = [];
  const norm = (v: unknown): unknown => {
    if (v === null || v === undefined || v === false) return "";
    // ACF returns false/"" for an empty repeater or gallery — normalize an
    // empty array to the same so "no rows" compares equal on both sides.
    if (Array.isArray(v)) return v.length ? v.map(norm) : "";
    if (typeof v === "object") {
      const o = v as Record<string, unknown>;
      if ("id" in o && ("url" in o || "source_url" in o || "mime_type" in o)) return o.id; // image/file/gallery item
      if ("ID" in o) return (o as any).ID; // post object
      const out: Record<string, unknown> = {};
      for (const [k, val] of Object.entries(o)) if (!k.endsWith("_source")) out[k] = norm(val);
      return out;
    }
    return v;
  };
  const expectNorm = (v: unknown): unknown => norm(v);

  for (const w of writes) {
    const live = await wp(`/pages/${w.page}?acf_format=standard&_fields=acf`);
    for (const [field, expected] of Object.entries(w.acf)) {
      const got = norm((live.acf ?? {})[field]);
      const want = expectNorm(expected);
      if (JSON.stringify(got) !== JSON.stringify(want)) {
        failures.push(`${w.label}.${field}\n  want ${JSON.stringify(want).slice(0, 200)}\n  got  ${JSON.stringify(got).slice(0, 200)}`);
      }
    }
  }

  if (failures.length) {
    console.error(`\nREAD-BACK MISMATCHES (${failures.length}):\n` + failures.join("\n"));
    process.exit(1);
  }
  console.log(`\nMIGRATION VERIFIED — ${writes.length} page payloads read back identical.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
